version: "3"
services:
  
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    #    environment:
    #     - PGADMIN_DEFAULT_EMAIL=
    #      - PGADMIN_DEFAULT_PASSWORD=
    env_file:
      - .env
    ports:
      - ${PGADMIN_OUT_PORT}:80
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin

  reservation-service:
    depends_on:
      - "postgres"
    build:
      context: .
      dockerfile: ./src/ReservationService/Dockerfile
    restart: always
    ports:
      - ${RESERVATION_SERVICE_OUT_PORT}:80
    env_file:
      - .env

volumes:
  db-data: